components/shared/Blocks/BookingButton.tsx
components/shared/NavBarClient.tsx

Fixed sizing of nav bar
- reduced height from 120px to 70px 
- reduce button vertical padding by 4px 
- vertically aligned all buttons and added small pb to the logo to get text aligned
- consistent spacing between nav items 
Test passed by @bettybondoc 
**Figure: new nav bar**

💄 Fix sizing of Nav Bar

---

.env.example
README.md

Several environment variables need to be set for `SSW.Products` to work.
This change add:
- An example `.env` file
- Details to README.md about how the example `.env` file should be copied to `.env` prior to starting the development server

🧑‍💻 DX - Adds .env.example to improve ease of setup

---

components/shared/Blocks/BookingButton.tsx
content/navBars/YakShaver/YakShaver-NavigationBar.json

cc: @uly1 @StefStar 
As per email from uly 
1. Consider changing the 'Get Your Project Started' call to action to something more specific, possibly by consulting with Steph.
2. Adjust the spacing to prevent the scroll bar from interacting with the X in the corner.
I have created a new JotForm that uses the same fields but has a different logo and headline than the SSW one. 
I have also added more spacing to prevent the scroll bar interacting with the 'X'

Change jotFormId + add padding

---

components/shared/BlogPostClient.tsx

To fix the breadcrumb alignment + margin.
As per reported by @adamcogan 
> Tiago
> https://yakshaver.ai/docs/recording-work-item-snagit
> 1. See red line on image - should the breadcrumb be top aligned?
> ![image0](https://github.com/user-attachments/assets/d6e1ff5b-69c1-4f79-949c-eaad8b9fb35f)

Improve breadcrumb UI

---

components/shared/Blocks/FeatureCarousel.tsx

XS change made from https://github.com/SSWConsulting/SSW.YakShaver/issues/916
**Figure: New Key Feature on Hover**
**Figure: Old Key Feature on Hover**

🐛 Fix Rounding of Feature Carousel

---

app/[product]/blog/[slug]/page.tsx
app/[product]/docs/[slug]/page.tsx
components/shared/Blocks/Features.tsx
components/shared/BlogPostClient.tsx
components/shared/DocPostClient.tsx
components/shared/FooterClient.tsx

Re-implemented the `useTina` hook to allow for live editing with the TIna client across all pages (targeting the /docs/<slug> and /blogs/<slug> pages)

Fix live editing for /docs and /blogs

---

components/shared/Blocks/Features.tsx

for the common phone size (w-390px) the hero was blocking weirdly onto two lines - dropping the text size by one allows the spacing to fit better on the 360-390px phones. 
**Figure: Mobile before**
**Figure: Mobile After**

drop text size by 1 for mobile to fit for smaller mobile devices

---

content/docs/EagleEye/how-to-add-a-new-tag.mdx
content/navBars/EagleEye/EagleEye-NavigationBar.json

This pull request includes changes to the EagleEye documentation and navigation bar. The most important changes include renaming and updating metadata in the documentation file and adding a new link to the navigation bar.
Documentation updates:
* [`content/docs/EagleEye/how-to-add-a-new-tag.mdx`](diffhunk://#diff-9af05c6af37d1c01a3c6f5e35bb7ec14049222747d913c69e22c06c44638664eL7-R7): Renamed from `content/blogs/EagleEye/how-to-add-a-new-tag.mdx`, updated the `date` field, and corrected a step number in the instructions. [[1]](diffhunk://#diff-9af05c6af37d1c01a3c6f5e35bb7ec14049222747d913c69e22c06c44638664eL7-R7) [[2]](diffhunk://#diff-9af05c6af37d1c01a3c6f5e35bb7ec14049222747d913c69e22c06c44638664eL23-R20)
Navigation bar update:
* …

EagleEye Move article from blog to docs

---

app/[product]/[filename]/page.tsx
app/[product]/blog/[slug]/page.tsx
app/[product]/blog/page.tsx
app/[product]/docs/[slug]/page.tsx
app/[product]/docs/page.tsx
app/[product]/page.tsx
components/shared/FooterServer.tsx

- Adds SSG to SSW Products - general site speedup! 
https://github.com/user-attachments/assets/d9032a36-9947-43c9-957a-bbaa87d3c187
**Figure: Page Load Improved as its not being Server Rendered anymore!** 
```
✓ Generating static pages (32/32)
✓ Collecting build traces
✓ Finalizing page optimization
Route (app)                                       Size     First Load JS
┌ ○ /_not-found                                   878 B          88.4 kB
├ ● /[product]                                    240 B          1.44 MB
├   ├ /EagleEye
├   ├ /TimePro
├   └ /YakShaver
├ ● /[product]/[filename]                         425 B          1.44 MB
├   ├ /EagleEye/home
├   ├ /TimePro/home
├   ├ /YakShaver/about
├   └ [+2 more paths]
├ ● /[product]/blog                               1.52 kB         118 kB …
```

Add generateStaticParams functions for pages, blogs, and docs

---

components/shared/NavBarClient.tsx
content/navBars/YakShaver/YakShaver-NavigationBar.json

As per https://github.com/SSWConsulting/SSW.YakShaver/issues/1642 we wanted to be able to render group items in the nav bar, this PR updates the nav bar to allow for this and fixes the UI for it too
**Group Items large nav bar**
**Group items small nav bar**

Fixed UI for rendering navigation group items

---

components/shared/Blocks/Calculator.tsx

small ui fixes to the calculator component
- Dropped text size for when custom is shown 
- Fixed spelling error 
**Figure: From Betty**

small Ui fixes

---

components/shared/Blocks/AnimatedBeam.tsx
components/shared/NavBarClient.tsx

As per https://github.com/SSWConsulting/SSW.YakShaver/issues/1806
Fixed the z-indexing for overlap of animated beam with navbar 
**Figure: No more collision**

Make Z Index for Navbar Maximum

---

content/pages/EagleEye/home.json

**Figure: Fixes this typo in the CTA description**

EagleEye - Fixing typo in Call To Action

---

components/shared/FooterClient.tsx

Update FooterClient.tsx to have padding on sides as well

---

components/shared/Blocks/ActionsButton.tsx
content/pages/EagleEye/home.json

Originated from PBI https://github.com/SSWConsulting/SSW.EagleEye/issues/1059
1. Use embedded YouTube video on EagleEye home page
2. Update action button to open in new tab. This has impact on :
a. EagleEye home page - "BOOK A DEMO" button
b. EagleEye home page - "SCHEDULE CALL" button
c. YakShaver about page - "SCHEDULE CALL" button

Improve user experience on EagleEye video and action buttons

---

content/blogs/YakShaver/how-much-time-does-yakshaver-save.mdx

change the roi calculator link to main page.
The ROI Calculator link was originally directed to Pricing page as Adam want the calculator there, however, it seems not going to happen for now as the discussion with the designers.
- #214

change the roi calculator link to main page

---

components/shared/BlogIndexClient.tsx

CC: @hveraus 
I've moved the author name on the blog index page to a separate line so that the name and date don't get smudged when the name is too long.
sorry @bettybondoc  ☹️
**Figure: Fixes this**

🐛 Card and author | move author to separate line

---

components/shared/Blocks/Calculator.tsx
content/pages/YakShaver/home.json

Resolves https://github.com/SSWConsulting/SSW.YakShaver/issues/1911
- "Credits" are now "credits"
- Remove the gradient on the hours
- Remove "Up to" in "Up to x" for work items on the calculator
- Reword "Your ROI with YakShaver" to "YakShaver Usage ROI"
**Figure: Highlighting the changes**
N/A

Improve ROI calculator clarity and consistency

---

README.md
app/[product]/sitemap.xml/route.ts
components/shared/FooterServer.tsx
middleware.ts
package.json
src/types/product-list.ts
src/types/tina.ts
utils/privacy.ts
utils/sitemap.ts
utils/tenancy.ts
utils/tina.ts
yarn.lock

**Note**: As we need to serve a different sitemap depending on the tenant the user is accessing, I was not able to use the [typical approach in Next.js](https://nextjs.org/docs/app/api-reference/file-conventions/metadata/sitemap) for generating a sitemap. I've instead created a route that will serve the appropriate sitemap.
https://github.com/SSWConsulting/SSW.YakShaver/issues/1145
**Figure: Sitemap for Yakshaver.ai**

🔍SEO - Add dynamic sitemap generator for all tenants

---

components/shared/BlogPostClient.tsx

CC: @louisroa8189 
This PR hides the banner image on blog pages when none is provided. I need to do this because the eagle eye blog doesn't have a banner image

fixed broken image on SSWEagleeye

---

components/utilityComponents/TypewriterAnimation.tsx

I noticed the highlight box for the typewriter animation gets sheared off on the left hand side so I fixed it. There were also several span tags not doing anything that I removed to make the code cleaner.
**❌Figure: Before**
**✅Figure: After**

fix cropping of typewriter highlighted words & cleaned up html

---

components/shared/YouTubeEmbed.tsx

as per @adamcogan 's **Re: EagleEye YouTube - click ◼️black play, then click 🟥 red play**
from
to

Update YouTubeEmbed.tsx to make play button red

---

content/pages/YakShaver/home.json

Remove the "No Credit Card Required" under the watch video button
|Before|After|
|-|-|
|<img width="1415" height="678" alt="image" src="https://github.com/user-attachments/assets/b1fc1e74-042f-4df0-b039-458f258eaf2d" />|<img width="1365" height="683" alt="image" src="https://github.com/user-attachments/assets/eef74219-3303-42b2-98f6-4b8f7f12d8f0" />|

remove credit card text

---

app/[product]/docs/[slug]/TableOfContentsClient.tsx
app/[product]/docs/[slug]/page.tsx

As per https://github.com/SSWConsulting/SSW.YakShaver/issues/2907 
**Figure: ❌ Before - max-h restricts nav items**
**Figure: ✅ After - max-h removed**

Fix max-height limit on nav items 

---

components/shared/NavBarClient.tsx
components/ui/button.tsx
content/navBars/YakShaver/YakShaver-NavigationBar.json

Currently the home page has only one button on navbar "Sign up for free" which confuses users about how to navigate to portal, or how to login to the system.
I've talked with @micsblank , and agreed to add "Log in" button which is more visible and indicates user to log into the system. We don't need to use extra "Portal" word on button because it is descriptive to us.
**Figure: Current navbar**
**Figure: New navbar**

Added login button to navbar to make visible for user
