SSWConsulting/SSW.Products

components/shared/Blocks/FAQ.tsx
components/shared/Blocks/FeatureCarousel.tsx
components/shared/Blocks/Features.tsx

as per https://github.com/SSWConsulting/SSW.YakShaver/issues/853 this pr fixes how the chromium browsers renders alot of the main components. 
The fix was to bump up the screen sizing classes 
test passed by @bettybondoc

bump screen sizing up

---

content/pages/YakShaver/about.json
content/pages/YakShaver/home.json
content/pages/YakShaver/pricing.json

addressing https://github.com/SSWConsulting/SSW.YakShaver/issues/779 
just fixing links on buttons

updating links

---

components/shared/Blocks/Banner.tsx
components/shared/Blocks/BookingButton.tsx
components/shared/Blocks/FeatureCarousel.tsx
components/shared/Blocks/Features.tsx
components/shared/Blocks/Pricing.tsx
components/shared/FooterClient.tsx
components/shared/NavBarClient.tsx

This PR addresses https://github.com/SSWConsulting/SSW.YakShaver/issues/782 
Changes: 
- more uniform x padding on mobile + tablet
- hamburger icon that allows nav bar to be collapsable for both tablet and mobile 
- fixed the footer so that it more closely matches our ssw site for table and mobile 
- fixed x padding on the pricing page so that we had no text clipping out of boundaries 
- implemented the sm and md logic from the feature component into the banner component so that in sm or md views the text is above the image not nexto eachother 
- fixed jotform view on sm mode

Mobile and Tablet Responsiveness 

---

components/shared/NavBarClient.tsx

as per my conversation with @bettybondoc  
- added a little bit of breathing room for the non scrolled 
- upped bg opacity of the hamburger open menu

More UI Changes to NavBar

---

components/shared/NavBarClient.tsx

change icons

---

app/[product]/layout.tsx
components/shared/Blocks/Banner.tsx
components/shared/Blocks/FAQ.tsx
components/shared/Blocks/FeatureCarousel.tsx
components/shared/Blocks/Features.tsx
components/shared/Blocks/Pricing.tsx
components/shared/BlogIndexClient.tsx
components/shared/BlogPostClient.tsx
components/shared/NavBarClient.tsx

This is a PR for https://github.com/SSWConsulting/SSW.YakShaver/issues/813
In this PR i am:

Changing Global Font + UI text changes

---

content/blogs/YakShaver/1.mdx
content/blogs/YakShaver/2.mdx
content/blogs/YakShaver/3.mdx
content/blogs/YakShaver/4.mdx
content/blogs/YakShaver/5.mdx
content/blogs/YakShaver/6.mdx
content/blogs/YakShaver/7.mdx
content/navBars/YakShaver/YakShaver-NavigationBar.json

@tomek-i 
Hiding the blog menu item and deleting test blog posts until we have a blog ready to post

Hide Blogs ** For now ** 

---

content/blogs/YakShaver/ai-at-comptia.mdx
content/navBars/YakShaver/YakShaver-NavigationBar.json

add blog back

---

middleware.ts

As per title, i spoke to Giles and Hugo about the middleware and have applied their feedback

Improve Middleware with Hugo and Giles feedback

---

app/[product]/.well-known/microsoft-identity-association.json

- Add domain verification for YakShaver to go public in marketplace.

✨ DNS - Add domain verification file

---

middleware.ts

try fix middleare search for .mdx file

upd mdware

---

app/[product]/.well-known/microsoft-identity-association.tsx

test file add

---

next.config.mjs

cc: @adamcogan @Lewkans @steven0x51 
Josh
1. Fix
https://yakshaver.ai/blog/recording-work-item-snagit
>404 - Page Not Found
>The page you are looking for does not exist.
-a
---------

🔌 Redirect from old /blog to new /docs 

---

next.config.mjs

adding another redirect from old blog posts that are now docs

add another redirect

---

components/shared/DocPostClient.tsx

(same as done on BLOGS on https://github.com/SSWConsulting/SSW.Products/pull/59)

Improve breadcrumb UI (Docs)

---

content/docs/YakShaver/how-to-use-yakshaver.mdx
content/docs/YakShaver/setting-up-other-recording-tools.mdx

Fix CTF Image and Update Title

---

components/shared/BlogIndexClient.tsx
components/shared/BlogPostClient.tsx
components/shared/DocPostClient.tsx
components/shared/DocsIndexClient.tsx

cc: @uly1, @adamcogan, @calumjs
To fix https://github.com/SSWConsulting/SSW.YakShaver/issues/1214

Improving blog and docs index view

---

content/pages/YakShaver/pricing.json

Email: RE: Pricing Page Confusion and Suggested Changes
Sender: @JimmyChenSSW 
- fix: price plan name
- fix: # of people so that it's clearer
@JimmyChenSSW

📄 Update YakShaver price plan name and # of people

---

components/shared/Background/InteractiveBackground.tsx

As per title - removes logic to do with the mouse-tracking bubble. Think site looks better without it (still has a dynamic background)

Remove mouse tracking bubble

---

components/shared/NavBarClient.tsx

The offset from the navigation bar was bugging me when users scrolled - so i decided to put a small fix to it. 
**Before**
https://github.com/user-attachments/assets/a254fee6-7a88-4696-a76f-b68ce6fb2721
**After**
https://github.com/user-attachments/assets/73cbc5f8-cd5e-4fa2-8128-afd4173e6e78

💄 Small UI + UX improvements to the scroll behaviour of the navigation bar

---

components/shared/FooterClient.tsx
content/footer/YakShaver/YakShaver-Footer.json

cc: @ricksu978 
As per our conversation, added dynamic year to the footer

added dynamic year to footer

---

app/[product]/layout.tsx

Whilst we only have analytics for a singular tenant for now, i have not gone through the route of adding the analytics as a variable of the tenancy environment variable. 
Rather we are just conditionally rendering the script based on the product

🔌 adding conditional script for Plausible

---

components/shared/Background/InteractiveBackground.scss

change from gray to black cc @louisroa8189

change from stale gray to black

---

content/pages/YakShaver/home.json

as per title, change from 
Sprint Review #12 
to
Meeting Transcript

Change Copy of Hero

---

app/api/leaderboard/route.ts
components/shared/Blocks/BentoBox.tsx
components/utilityComponents/TimeSavedCounter.tsx
components/utilityComponents/YaksShavedCounter.tsx

Hooked the current counter boxes to the public YaksShaved endpoint

🔌 Hook Bento to API

---

app/[product]/[filename]/page.tsx

This pull request includes a small change to the `app/[product]/[filename]/page.tsx` file. The change adds a revalidation time for the page to ensure it is refreshed every 60 seconds.
* `app/[product]/[filename]/page.tsx`: Added `export const revalidate = 60;` to set the revalidation time for the page. ([app/[product]/[filename]/page.tsxR73-R74](diffhunk://#diff-3e5c1f23f52d9515eb183aaed80d28d825d1c0cee021cba1c2ab27467dc3907aR73-R74))

Set revalidation time to 60 seconds for page data

---

components/shared/Blocks/Hero.tsx

Fix button links

---

components/shared/Blocks/Hero.tsx
content/pages/YakShaver/roadmap.json

as per title - added agentic workflow to the roadmap 
(also fixed the bg of the homepage hero component)

Add agentic workflow to roadmap

---

.env.example
app/[product]/layout.tsx
utils/getGoogleTagId.tsx

Added a check for the google tag manager id in the product list, 
Tested and working for YakShaver on staging 
**Figure: GA ID showing on staging successfully**

Added Multi-Tenancy GTM

---

app/globals.css
content/docs/YakShaver/recording-work-item-snipping-tool.mdx
tina/tinamarkdownStyles/DocAndBlogMarkdownStyle.tsx

As per @adamcogan 's https://github.com/SSWConsulting/SSW.YakShaver/issues/1679

Improving styling

---

tailwind.config.js

added `./tina/*` to tailwind config file

Fix styles tailwind cfg

---

components/shared/FooterClient.tsx
components/shared/FooterServer.tsx
package.json

I added a per tenant privacy policy link to the banner footer. If a particular tenant does not have a privacy policy the link will not render.
[Fixed #1769](github.com/SSWConsulting/SSW.Yakshaver/issues/1769)
**Figure: Privacy policy link for YakShaver**

📃Added link to privacy policy in footer

---

components/shared/Blocks/Calculator.tsx
components/shared/Blocks/CardAndImage/CardAndImage.tsx
components/shared/FooterServer.tsx

As per https://github.com/SSWConsulting/SSW.YakShaver/issues/1831, made sure that the active image is always the id of the last item that was opened

fix bug and rm logs

---

components/shared/Blocks/Hero.tsx
components/shared/Blocks/Pricing.tsx
content/pages/YakShaver/home.json

padding fixes from sprint review

sprint review padding changes

---

components/shared/NavBarClient.tsx
tailwind.config.js

See https://github.com/SSWConsulting/SSW.YakShaver/issues/1869
Test on staging

fix navbar

---

components/ui/MockYakShaverCards.tsx

as per conversation in sprint review, increase RHS delay time

increase delay time

---

components/shared/NavBarClient.tsx

The navbar was broken when we fixed a stacking issue in this PR: https://github.com/SSWConsulting/SSW.Products/pull/164
This PR updates the media queries so that it appears on mobile/tablet view

🐛Navbar - Add missing navbar on mobile devices

---

components/shared/Blocks/Calculator.tsx

cc: @tiagov8 
as per https://github.com/SSWConsulting/SSW.YakShaver/issues/1876
**Changes**

Pricing / ROI - add reccomended badge

---

components/shared/Blocks/CardAndImage/CardAndImage.tsx
content/pages/YakShaver/home.json

cc: @tiagov8 
As per https://github.com/SSWConsulting/SSW.YakShaver/issues/1873
**Changes**
**Figure: Changes made**

How it works component - Change text + add tick

---

content/pages/YakShaver/home.json

uly suggested change

---

content/pages/YakShaver/home.json

✏️Fix "snaggit" typo in How it works badge

---

components/shared/Blocks/Hero/GradientBackground.tsx

As per feedback from @adamcogan I've made the purple background sun smaller

Make purple gradient effect smaller

---

components/shared/Blocks/Hero/GradientBackground.tsx

CC:
@hveraus I made the gradient background transparent & made it reach a little bit further as per feedback from Ken.

moved background to the right & reduced opacity

---

components/shared/Blocks/Hero/GradientBackground.tsx

fixed background using webkit transform

---

content/docs/YakShaver/frequently-asked-questions.mdx

quick formatting fixes cause it looks bad

FAQ formatting fixes

---

content/docs/YakShaver/video-hosting.mdx

- Add info about video hosting
- Add content on upcoming feature https://github.com/SSWConsulting/SSW.YakShaver/issues/1768

Add Video Hosting docs

---

content/pages/YakShaver/home.json

Fixing the inconsistent "i's" in the how it works component.

Tina/fix i in boxes 

---

components/shared/BlogPostClient.tsx
content/docs/YakShaver/recording-work-item-teams.mdx
tina/tinamarkdownStyles/DocAndBlogMarkdownStyle.tsx

as per @adamcogan 's **Improvements Needed for YakShaver Documentation** via YakShaver

Improve Docs and Blog posts look and feel and wording

---

content/pages/YakShaver/try-it-now.json

Fixes https://github.com/SSWConsulting/SSW.YakShaver/issues/1929
**Figure: Updated try it now page instructions**

✨Try it now page - update recording instructions

---

components/shared/NavBarClient.tsx

As per https://github.com/SSWConsulting/SSW.YakShaver/issues/1916 - keeping arrow item always pointing downward in Navbar

Keep Arrow Down

---

content/pages/YakShaver/roadmap.json

remove curly brackets from roadmap

---

components/shared/Blocks/BookingButton.tsx

Fixes https://github.com/SSWConsulting/SSW.EagleEye/issues/1071

Fix JotForm issue for China users

---

content/pages/YakShaver/try-it-now.json

fix the pin image in try-now doesn't show up

Yakshaver - Try it now - replace the pin image to show correctly on prod

---

content/blogs/YakShaver/how-much-time-does-yakshaver-save.mdx

added image and reordered text with Louis

TinaCMS content update

---

content/docs/EagleEye/webhooks.mdx
content/docsTableOfContents/EagleEye/toc.mdx

**Screenshot**
**Figure: added webhook section in Docs**

Added webhooks page to menu in docs

---

components/shared/Blocks/FAQ.tsx

Fixed: https://github.com/SSWConsulting/SSW.YakShaver/issues/1961
**Figure: Accordion with multiple items open**

💄Accordion - Allow user to open multiple items simultaneously

---

components/shared/Blocks/BentoBox/BentoBox.tsx
components/utilityComponents/TimeSavedCounter.tsx
content/pages/YakShaver/home.json

improved the readability for bento box as per the request by Tiago
[- #1887](https://github.com/SSWConsulting/SSW.YakShaver/issues/1887)

1887 readability bento box

---

app/[product]/docs/[slug]/DocPostClient.tsx
content/docs/YakShaver/support.mdx
content/docsTableOfContents/YakShaver/toc.mdx
content/navBars/YakShaver/YakShaver-NavigationBar.json

CC: @calumjs, @louisroa8189 
In order instill confidence in our users I've added a support page to our documentation. This page tells users how they can reach out to the YakShaver team.
This support page can be accessed via the nav bar at **community | support**
**Figure: community support page**

📃New Page - Yakshaver support page

---

content/docs/YakShaver/connect-your-youtube-channel-to-a-project.mdx
content/docs/YakShaver/make-uploads-permanent.mdx
content/docsTableOfContents/YakShaver/toc.mdx

Email Subject: `YakShaver - lost a video 🟥`
Added doc to explain why videos get expired, and how to resolve
Updated Youtube doc to explain why it's good to do so
No

Add new doc - Managing Video Expiration and Making Uploads Permanent

---

content/docs/YakShaver/make-uploads-permanent.mdx
content/docsTableOfContents/YakShaver/toc.mdx

Feedback from @steven0x51
No SEO
updated SEO
updated ToC heading name
No

Updated Doc title and add SEO

---

content/docs/YakShaver/add-azure-devops-projects.mdx
content/docsTableOfContents/YakShaver/toc.mdx

https://github.com/SSWConsulting/SSW.YakShaver/issues/2347
Created documentation for adding DevOps projects to YakShaver
N/A

Create add azure dev ops projects doc

---

app/[product]/docs/[slug]/DocPostClient.tsx
app/[product]/docs/[slug]/page.tsx

Resolves https://github.com/SSWConsulting/SSW.EagleEye/issues/1257
**Figure: Added spacing before Last Updated**

💄 Add spacing before last updated

---

app/[product]/docs/[slug]/DocPostClient.tsx
app/[product]/docs/[slug]/page.tsx
app/[product]/docs/layout.tsx

Fixes https://github.com/SSWConsulting/SSW.Products/issues/345

Update blog/docs page view to allow more space for next and previous links

---

content/pages/YakShaver/home.json

as per @adamcogan 's request on **YakShaver - Record issues & let AI instantly assign them to the right team**

Update home.json to break a line after "reports"

---

components/NavBar/MobileMenu.tsx

Fixes https://github.com/SSWConsulting/SSW.EagleEye/issues/1281
**Figure: After fix, Lighthouse report shows 100 score**

Add accessibility label on mobile menu toggle

---

app/[product]/blog/[slug]/page.tsx
content/blogs/YakShaver/ai-at-comptia.mdx
content/blogs/YakShaver/how-much-time-does-yakshaver-save.mdx
content/blogs/YakShaver/new-support-macos.mdx
content/blogs/YakShaver/optimising-video-file-size.mdx
content/blogs/YakShaver/what-is-yakshaver.mdx
content/blogs/YakShaver/zh/ai-at-comptia.mdx
content/blogs/YakShaver/zh/how-much-time-does-yakshaver-save.mdx
content/blogs/YakShaver/zh/new-support-macos.mdx
content/blogs/YakShaver/zh/optimising-video-file-size.mdx
content/blogs/YakShaver/zh/what-is-yakshaver.mdx
content/docs/YakShaver/frequently-asked-questions.mdx

Fixing manually written "Blogs"

Fix SEO for Blog Pages

---

README.md

Add mention of branding sites "Powered By Tina" as per Adam's email "Re: YakShaver - homepage should advertise it is built with Tina"

Update README with product page guidelines

---

app/[product]/docs/layout.tsx

Fixes https://github.com/SSWConsulting/SSW.Products/issues/495

Adjust layout styles for the left column
